macro(list_subdirectories result curdir)
  file(GLOB children RELATIVE ${curdir} ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
      list(APPEND dirlist ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()

macro(add_all_subdirectories)
    list_subdirectories(dirs ${CMAKE_CURRENT_SOURCE_DIR})
    foreach(dir IN LISTS dirs)
        add_subdirectory(${dir})
    endforeach()
endmacro()